CREATE TABLE LEX.ABOGADOS 
(
  ABOGADID VARCHAR2(20) NOT NULL
, NOMBRES VARCHAR2(80) NOT NULL 
, APELLIDOA VARCHAR2(30) NOT NULL 
, APELLIDOB VARCHAR2(30) NOT NULL 
, TELEFONO VARCHAR2(10) NOT NULL 
, EMAIL VARCHAR2(80) NOT NULL 
, USERNAME VARCHAR2(25) NOT NULL
, PASSWORD VARCHAR2(25) NOT NULL
, CONSTRAINT ABOGADID_PK PRIMARY KEY 
  (
    ABOGADID 
  ) 
);

CREATE TABLE LEX.CASOS
(
    CASOID VARCHAR2(20) NOT NULL  
,   CASONAME VARCHAR2(20) NOT NULL
,   DESCRIPT VARCHAR2(255)
,   CASODATE DATE NOT NULL
,   CASOTYPE VARCHAR2(20) NOT NULL
,   ESTADO VARCHAR2(20) NOT NULL
,   ABOGADID VARCHAR2(20)
,   FOREIGN KEY (ABOGADID) REFERENCES LEX.ABOGADOS(ABOGADID)
,   CONSTRAINT CASOID_PK PRIMARY KEY 
  (
    CASOID 
  ) 
);

CREATE TABLE LEX.CASODOC 
(
     CASOID VARCHAR2(20)
,    RUTA VARCHAR2(255) 
,    FOREIGN KEY (CASOID) REFERENCES LEX.CASOS(CASOID)
);
